### ISSUE TITLE
Error Exception with user permission

### ISSUE THREAD

**Issue by ghost** [jrrdnx/craft-helpdesk-support#4]
Hi @jrrdnx ,

i must unfortunately report another bug. It occurs if a user, who have permission to manage Helpdesk, goes to Helpdesk page, he will receive this "internal server error", in dev mode i receive this error exception:
```
Undefined offset: 0
1. in /var/www/craft/vendor/jrrdnx/helpdesk-support/src/services/ZendeskSupport.phpat line 84
75767778798081828384858687888990919293    
public function getCurrentUser()
    {
        $curl = HelpdeskSupport::$plugin->core->curlInit($this->getUrl("users/search.json?query=" . Craft::$app->getUser()->getIdentity()->email), $this->getAuthOption(), $this->getAuthString());
        $response = HelpdeskSupport::$plugin->core->curlExec($curl);
        if($response["http_code"] !== 200)
        {
            return null;
        }
 
        return json_decode($response["data"])->users[0];
```

Thank you in advance for your support!

Hoang Ta

**Comment by jrrdnx** [comment]
@hoangngt Sorry for the delay, I've been out due to the holidays.

I'm working on adding some additional error handling, but unfortunately my Zendesk account isn't working at the moment.

Do you have the ability to see what `$response["data"]` looks like? If `users` is an empty array, it would seem that the email address you're searching by (the email address of the Craft user) doesn't match any users in the Zendesk account.

**Comment by ghost** [comment]
Hi @jrrdnx, I saw that you wrapped it with error handling. But I think it isn't necessary that an user in craft must have Zendesk account. For example: anonymous can also submit a ticket, you need there only email and name of submitter, not the requester_id. Do you intent to support anonymous ticket submitter? We indeed need this function.
Thank you!

**Comment by jrrdnx** [comment]
@hoangngt Opened a new issue regarding anonymous submitters: #5
